bitskins:
  appId: c0eef4118084f8164bec65e6253bf195
  apiKey: 4578dbd1-e3fd-44a9-8e57-d83e986ef602
  wsPort: 443
  wssPort: 443
  host: notifier.bitskins.com
  encrypted: true

logging:
  level:
    root: info

spring:
  application:
    name: bitskins-api
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
      show_sql: true
  datasource:
    url: jdbc:h2:mem:bitskin-apis;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: zhuonima
    password: bitskin@19930112tz
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /admin
management:
  security:
    enabled: false


